-- VHDL netlist generated by SCUBA Diamond (64-bit) 3.11.0.396.4
-- Module  Version: 5.8
--C:\lscc\diamond\3.11_x64\ispfpga\bin\nt64\scuba.exe
--w -n FIFOx64 -lang vhdl -synth lse -bus_exp 7 -bb -arch xo2c00 
--type ebfifo -depth 512 -width 16 -rwidth 16 -no_enable -pe 10 -pf 508 

-- Wed Jun 10 22:38:12 2020

LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
-- synopsys translate_off
LIBRARY MACHXO2;
USE MACHXO2.components.ALL;
-- synopsys translate_on

ENTITY FIFOx64 IS
    PORT (
        Data        : IN std_logic_vector(15 DOWNTO 0);
        WrClock     : IN std_logic;
        RdClock     : IN std_logic;
        WrEn        : IN std_logic;
        RdEn        : IN std_logic;
        Reset       : IN std_logic;
        RPReset     : IN std_logic;
        Q           : OUT std_logic_vector(15 DOWNTO 0);
        Empty       : OUT std_logic;
        Full        : OUT std_logic;
        AlmostEmpty : OUT std_logic;
        AlmostFull  : OUT std_logic);
END FIFOx64;

ARCHITECTURE Structure OF FIFOx64 IS

    -- internal signal declarations
    SIGNAL scuba_vhi : std_logic;
    SIGNAL Empty_int : std_logic;
    SIGNAL Full_int  : std_logic;
    SIGNAL scuba_vlo : std_logic;

    -- local component declarations
    COMPONENT VHI
        PORT (Z : OUT std_logic);
    END COMPONENT;
    COMPONENT VLO
        PORT (Z : OUT std_logic);
    END COMPONENT;
    COMPONENT FIFO8KB
        GENERIC (
            FULLPOINTER1        : IN STRING;
            FULLPOINTER         : IN STRING;
            AFPOINTER1          : IN STRING;
            AFPOINTER           : IN STRING;
            AEPOINTER1          : IN STRING;
            AEPOINTER           : IN STRING;
            ASYNC_RESET_RELEASE : IN STRING;
            RESETMODE           : IN STRING;
            GSR                 : IN STRING;
            CSDECODE_R          : IN STRING;
            CSDECODE_W          : IN STRING;
            REGMODE             : IN STRING;
            DATA_WIDTH_R        : IN INTEGER;
            DATA_WIDTH_W        : IN INTEGER);
        PORT (
            DI0    : IN std_logic;
            DI1    : IN std_logic;
            DI2    : IN std_logic;
            DI3    : IN std_logic;
            DI4    : IN std_logic;
            DI5    : IN std_logic;
            DI6    : IN std_logic;
            DI7    : IN std_logic;
            DI8    : IN std_logic;
            DI9    : IN std_logic;
            DI10   : IN std_logic;
            DI11   : IN std_logic;
            DI12   : IN std_logic;
            DI13   : IN std_logic;
            DI14   : IN std_logic;
            DI15   : IN std_logic;
            DI16   : IN std_logic;
            DI17   : IN std_logic;
            CSW0   : IN std_logic;
            CSW1   : IN std_logic;
            CSR0   : IN std_logic;
            CSR1   : IN std_logic;
            FULLI  : IN std_logic;
            EMPTYI : IN std_logic;
            WE     : IN std_logic;
            RE     : IN std_logic;
            ORE    : IN std_logic;
            CLKW   : IN std_logic;
            CLKR   : IN std_logic;
            RST    : IN std_logic;
            RPRST  : IN std_logic;
            DO0    : OUT std_logic;
            DO1    : OUT std_logic;
            DO2    : OUT std_logic;
            DO3    : OUT std_logic;
            DO4    : OUT std_logic;
            DO5    : OUT std_logic;
            DO6    : OUT std_logic;
            DO7    : OUT std_logic;
            DO8    : OUT std_logic;
            DO9    : OUT std_logic;
            DO10   : OUT std_logic;
            DO11   : OUT std_logic;
            DO12   : OUT std_logic;
            DO13   : OUT std_logic;
            DO14   : OUT std_logic;
            DO15   : OUT std_logic;
            DO16   : OUT std_logic;
            DO17   : OUT std_logic;
            EF     : OUT std_logic;
            AEF    : OUT std_logic;
            AFF    : OUT std_logic;
            FF     : OUT std_logic);
    END COMPONENT;
    ATTRIBUTE syn_keep                  : BOOLEAN;
    ATTRIBUTE NGD_DRC_MASK              : INTEGER;
    ATTRIBUTE NGD_DRC_MASK OF Structure : ARCHITECTURE IS 1;

BEGIN
    -- component instantiation statements
    scuba_vhi_inst : VHI
    PORT MAP(Z => scuba_vhi);

    scuba_vlo_inst : VLO
    PORT MAP(Z => scuba_vlo);

    FIFOx64_0_0 : FIFO8KB
    GENERIC MAP(
        FULLPOINTER1 => "0b01111111110000", FULLPOINTER => "0b10000000000000",
        AFPOINTER1 => "0b01111110110000", AFPOINTER => "0b01111111000000",
        AEPOINTER1 => "0b00000010110000", AEPOINTER => "0b00000010100000",
        ASYNC_RESET_RELEASE => "SYNC", GSR => "DISABLED", RESETMODE => "ASYNC",
        REGMODE => "NOREG", CSDECODE_R => "0b11", CSDECODE_W => "0b11",
        DATA_WIDTH_R => 18, DATA_WIDTH_W => 18)
    PORT MAP(
        DI0 => Data(0), DI1 => Data(1), DI2 => Data(2), DI3 => Data(3),
        DI4 => Data(4), DI5 => Data(5), DI6 => Data(6), DI7 => Data(7),
        DI8 => Data(8), DI9 => Data(9), DI10 => Data(10), DI11 => Data(11),
        DI12 => Data(12), DI13 => Data(13), DI14 => Data(14),
        DI15 => Data(15), DI16 => scuba_vlo, DI17 => scuba_vlo,
        CSW0 => scuba_vhi, CSW1 => scuba_vhi, CSR0 => scuba_vhi,
        CSR1 => scuba_vhi, FULLI => Full_int, EMPTYI => Empty_int,
        WE => WrEn, RE => RdEn, ORE => RdEn, CLKW => WrClock, CLKR => RdClock,
        RST => Reset, RPRST => RPReset, DO0 => Q(9), DO1 => Q(10),
        DO2 => Q(11), DO3 => Q(12), DO4 => Q(13), DO5 => Q(14), DO6 => Q(15),
        DO7 => OPEN, DO8 => OPEN, DO9 => Q(0), DO10 => Q(1), DO11 => Q(2),
        DO12 => Q(3), DO13 => Q(4), DO14 => Q(5), DO15 => Q(6), DO16 => Q(7),
        DO17 => Q(8), EF => Empty_int, AEF => AlmostEmpty, AFF => AlmostFull,
        FF => Full_int);

    Empty <= Empty_int;
    Full  <= Full_int;
END Structure;

-- synopsys translate_off
LIBRARY MACHXO2;
CONFIGURATION Structure_CON OF FIFOx64 IS
    FOR Structure
        FOR ALL : VHI USE ENTITY MACHXO2.VHI(V);
    END FOR;
    FOR ALL : VLO USE ENTITY MACHXO2.VLO(V);
END FOR;
FOR ALL : FIFO8KB USE ENTITY MACHXO2.FIFO8KB(V);
END FOR;
